#!/bin/bash
rm -rf dist
VERSION=`git describe --tags`
python2 setup-release.py py2app
hdiutil create -fs HFS+ -volname "Electrum-LBTC" -srcfolder dist/Electrum-LBTC.app dist/electrum-lbtc-$VERSION.dmg

